---------------------------
-- VALIDATION
--    1  Row Count Validation
--    2. Primary key 
--    3. Route
--    4. Date
---------------------------

---------------------------
-- 0. CONTEXT
---------------------------
USE ROLE CANDIDATE_00342;
USE WAREHOUSE WH_CANDIDATE_00342;
USE DATABASE RECRUITMENT_DB;
USE SCHEMA CANDIDATE_00342;

---------------------------
-- 1. ROW COUNT RECONCILIATION
---------------------------

-- 1.1 STAGING VS FACT
SELECT
    (SELECT COUNT(*) FROM "STG_FLIGHTS")     AS STG_ROWS,
    (SELECT COUNT(*) FROM "FACT_FLIGHTS")    AS FACT_ROWS,
    (SELECT COUNT(*) FROM "VW_FLIGHTS")      AS VW_FLIGHTS_ROWS;


---------------------------
-- 2. PRIMARY KEY / UNIQUENESS CHECKS
---------------------------

-- 2.1 FACT_FLIGHTS TRANSACTIONID UNIQUENESS

SELECT "TRANSACTIONID", COUNT(*) AS CNT
FROM "FACT_FLIGHTS"
GROUP BY "TRANSACTIONID"
HAVING COUNT(*) > 1    --show non-unique
ORDER BY CNT DESC;

-- 2.2 DIM_AIRLINE CODE

SELECT 'DIM_AIRLINE' AS TABLE_NAME,
       COUNT(*) AS TOTAL_ROWS,
       COUNT(DISTINCT "AIRLINECODE") AS DISTINCT_AIRLINECODE
FROM "DIM_AIRLINE"
UNION ALL
SELECT 'STG_FLIGHTS',
       COUNT(*),
       COUNT(DISTINCT "AIRLINECODE")
FROM "STG_FLIGHTS";

-- 2.3 DIM_AIRPORT CODE UNIQUENESS
SELECT
    COUNT(*) AS TOTAL_ROWS,
    COUNT(DISTINCT "AIRPORTCODE") AS DISTINCT_AIRPORTCODE
FROM "DIM_AIRPORT";

-- 2.4 DIM_DATE CODE UNIQUENESS
SELECT
    COUNT(*) AS TOTAL_ROWS,
    COUNT(DISTINCT "DATEID") AS DISTINCT_DATEID
FROM "DIM_DATE";

-- 2.4 DIM_ROUTE CODE UNIQUENESS
SELECT
    COUNT(*) AS TOTAL_ROWS,
    COUNT(DISTINCT "DROUTEID") AS DISTINCT_ROUTEID
FROM "DIM_ROUTE";

---------------------------
-- 4. REFERENTIAL INTEGRITY CHECKS
--   view if any dim tables contain keys missing from fact
---------------------------

-- 4.1 FACT_FLIGHTS → DIM_AIRLINE: 
SELECT DISTINCT f."AIRLINECODE"
FROM "FACT_FLIGHTS" f
LEFT JOIN "DIM_AIRLINE" a
    ON f."AIRLINECODE" = a."AIRLINECODE"
WHERE a."AIRLINECODE" IS NULL;

-- 4.2 FACT_FLIGHTS → DIM_AIRPORT (ORIG)
SELECT DISTINCT f."ORIGINAIRPORTCODE"
FROM "FACT_FLIGHTS" f
LEFT JOIN "DIM_AIRPORT" ao
    ON f."ORIGINAIRPORTCODE" = ao."AIRPORTCODE"
WHERE ao."AIRPORTCODE" IS NULL;

-- 4.3 FACT_FLIGHTS → DIM_AIRPORT (DEST)
SELECT DISTINCT f."DESTAIRPORTCODE"
FROM "FACT_FLIGHTS" f
LEFT JOIN "DIM_AIRPORT" ad
    ON f."DESTAIRPORTCODE" = ad."AIRPORTCODE"
WHERE ad."AIRPORTCODE" IS NULL;

-- 4.4 FACT_FLIGHTS → DIM_DATE
SELECT DISTINCT f."DATEID"
FROM "FACT_FLIGHTS" f
LEFT JOIN "DIM_DATE" d
    ON f."DATEID" = d."DATEID"
WHERE d."DATEID" IS NULL;

-- 4.5 FACT_FLIGHTS → DIM_ROUTE
SELECT DISTINCT f."ROUTEID"
FROM "FACT_FLIGHTS" f
LEFT JOIN "DIM_ROUTE" r
    ON f."ROUTEID" = r."ROUTEID"
WHERE r."ROUTEID" IS NULL;
